spring:
  application:
    name: simple-service

  profiles:
    active:
    - dev
    
#disable basic authentication as spring cloud enables it by default
security:
  basic:
    enabled: false

#disable registering with eureka when running locally    
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

endpoints:
  routes:
    sensitive: false
    
management:
  security:
    enabled: false   

server:
  port: 8081
 
---
spring:
    profiles: dev

ribbon: 
  ConnectTimeout: 30000
  ReadTimeout: 10000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true

#disable registering with eureka when running locally    
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
